import type { Metadata } from 'next'
import Navbar from './components/navbar'
import ContentWrapper from './components/content'
import Footer from './components/footer'
import { Inter } from 'next/font/google'
import './styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'steve-and-sons-electric',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
				<Navbar />
				<ContentWrapper>{children}</ContentWrapper>
				<Footer />
      </body>
    </html>
  );
}
